name: yvensb.co
favicon: null
layout_spectrum: 0.75216
typography_spectrum: 0.28222180949524045
title: Maternity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161616'
    - '#141414'
    - '#000000'
    - '#141414'
    - '#0e0e0e'
  brandStrength: 0.08239283156581223
  lightness: 0.44867469603195786
  saturation: 0.5595280497800559
  rhythmicContrast: 0.316941229859367
purpose: []
