name: yvensb.co
favicon: null
layout_spectrum: 0.8436659772414714
typography_spectrum: 0.28222180949524045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.08239283156581223
  lightness: 0.44867469603195786
  saturation: 0.5595280497800559
  rhythmicContrast: 0.316941229859367
purpose: []
